[build]
  publish = "."
  command = "npm run build"

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/public/**.html"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[headers]]
  for = "/sitemap.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/font-preview.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
[[redirects]]
  from = "/font/*"
  to = "/public/font/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/img/*"
  to = "/public/img/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200
  force = true
[[headers]]
  for = "/public/encrypted/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"